### ISSUE TITLE
Is there any command only for inference? codes in main.sh are all used for training

### ISSUE THREAD

**Issue by Henry0528** [anthonyweidai/SvANet#1]

**Comment by anthonyweidai** [comment]
Please wait for several days. I need to revise the manuscript for now. After that, I will write a tutorial for how to conduct inference. Stay tuned.

**Comment by anthonyweidai** [comment]
https://github.com/anthonyweidai/SvANet/commit/e9d0a1ae112818aaa5ab527d1223e9f32fdace0b
