### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gudukuaile** [anthonyweidai/SvANet#13]
我在windows上安装的环境，
执行python main.py --task segmentation --gpus 0 --setname FIVES --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-11ad3fa6.pth这个命令之后报错，用的是fives数据集。
Traceback (most recent call last):
  File "D:\my_code\SvANet-main\main.py", line 179, in <module>
    opt = paramsInit(opt)
  File "D:\my_code\SvANet-main\lib\params_init\paramsInit.py", line 118, in paramsInit
    opt.pretrained_weight = [WeightPath for WeightPath in WeightPool \
IndexError: list index out of range
这是什么原因？还需要下载其他的文件吗？
![Snipaste_2024-10-12_17-23-06](https://github.com/user-attachments/assets/12e81302-747d-4ef3-a4b6-872fd8b50e89)

**Comment by anthonyweidai** [comment]
Prior to commencing the training, ensure that you have downloaded the pretrained model from [torchvision](https://download.pytorch.org/models/resnet50-11ad3fa6.pth).
@https://github.com/anthonyweidai/SvANet/issues/2
