### ISSUE TITLE
How can I download the pretrained model?

### ISSUE THREAD

**Issue by Stupid-wangnz** [anthonyweidai/SvANet#2]
How can I download the pretrained model mentioned in the training script. "--pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth"

**Comment by Stupid-wangnz** [comment]
I didn't see any information about which pretrained model the encoder model used in the paper, maybe I overlooked it. May I ask if you can provide more information about the pretrained encoder used.

**Comment by silentyuchen** [comment]
I'm using wide-resnet-50-2-export-5ae25d50.pth, it works

**Comment by anthonyweidai** [comment]
We used pretrained model downloaded from torchvision [official website](https://pytorch.org/vision/stable/_modules/torchvision/models/resnet.html#ResNet50_Weights). For resnet50-2.pth, you can download it by this [link](https://download.pytorch.org/models/resnet50-11ad3fa6.pth).

**Comment by anthonyweidai** [comment]
The difference between [IMAGENET1K_V1](https://github.com/pytorch/vision/tree/main/references/classification#resnet) and [IMAGENET1K_V2](https://github.com/pytorch/vision/issues/3995#issuecomment-1013906621) version of the pretrained model lies in different training configurations.
